/*
 Navicat Premium Data Transfer

 Source Server         : Oracle
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Host           : localhost:1521
 Source Schema         : C##INSLIB

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 21/02/2022 00:27:27
*/


-- ----------------------------
-- Table structure for BOOK
-- ----------------------------
--DROP TABLE "C##INSLIB"."BOOK";
CREATE TABLE "C##INSLIB"."BOOK" (
  "BOOK_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "BOOK_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "AUTHOR_ID" VARCHAR2(5 BYTE) VISIBLE,
  "PUBLISHER_NAME" VARCHAR2(255 BYTE) VISIBLE,
  "STATUS" VARCHAR2(255 BYTE) VISIBLE,
  "DATE_OF_ARRIVAL" DATE VISIBLE,
  "YEAR" NUMBER VISIBLE,
  "EDITION" VARCHAR2(255 BYTE) VISIBLE,
  "NO_OF_PAGES" NUMBER VISIBLE,
  "ADMIN_ID" VARCHAR2(255 BYTE) VISIBLE,
  "LANGUAGE" VARCHAR2(255 BYTE) VISIBLE,
  "BOOK_TYPE" VARCHAR2(255 BYTE) VISIBLE,
  "COVER_IMAGE" VARCHAR2(2550 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
ENABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of BOOK
-- ----------------------------
INSERT INTO "C##INSLIB"."BOOK" VALUES ('12', 'CHACHA KAHINI', 'SMA', 'HAKKANI', 'AVAILABLE', TO_DATE('2022-02-13 22:31:34', 'SYYYY-MM-DD HH24:MI:SS'), '2008', 'THIRD', '234', 'AD1', 'BANGLA', 'OTHER', 'https://bdebooks.com/wp-content/uploads/2019/09/15778722.jpg');
INSERT INTO "C##INSLIB"."BOOK" VALUES ('14', 'ITOL BITOL', 'SUKA', 'KOTHAMALA', 'AVAILABLE', TO_DATE('2022-02-08 15:38:33', 'SYYYY-MM-DD HH24:MI:SS'), '2008', NULL, '50', 'AD1', 'BANGLA', 'others', 'https://i.ytimg.com/vi/BZUN-wTbGl4/maxresdefault.jpg');
INSERT INTO "C##INSLIB"."BOOK" VALUES ('13', 'SESER KOBITA', 'RNT', 'KOTHAMALA', 'AVAILABLE', TO_DATE('2022-01-10 19:43:58', 'SYYYY-MM-DD HH24:MI:SS'), '2016', 'SECOND', '120', 'AD1', 'BANGLA', 'OTHER', 'https://ds.rokomari.store/rokomari110/ProductNew20190903/260X372/23f2f82cb_41029.jpg');
INSERT INTO "C##INSLIB"."BOOK" VALUES ('11', 'DESE BIDESE', 'SMA', 'HAKKANI', 'AVAILABLE', TO_DATE('2022-01-31 22:31:24', 'SYYYY-MM-DD HH24:MI:SS'), '2008', 'THIRD', '164', 'AD1', 'BANGLA', 'OTHER', 'https://1.bp.blogspot.com/-azI7RfXYCYM/VL5GQH6hJrI/AAAAAAAAAmQ/-3cK9QmpCD4/s1600/desh%2Bbideshe%2Bby%2Bsayed%2Bmostoba%2Bali.jpg');
INSERT INTO "C##INSLIB"."BOOK" VALUES ('21', 'COLLEGE ALGEBRA', 'NAS', 'SIMON AND SCHUSTER', 'AVAILABLE', TO_DATE('2022-02-01 11:54:06', 'SYYYY-MM-DD HH24:MI:SS'), '2019', 'SECOND', '204', 'AD1', 'ENGLISH', 'ACADEMIC', 'https://i.pinimg.com/originals/14/df/43/14df437e93ef277b0771bc46964c663c.jpg');

-- ----------------------------
-- Primary Key structure for table BOOK
-- ----------------------------
ALTER TABLE "C##INSLIB"."BOOK" ADD CONSTRAINT "SYS_C007677" PRIMARY KEY ("BOOK_ID");

-- ----------------------------
-- Checks structure for table BOOK
-- ----------------------------
ALTER TABLE "C##INSLIB"."BOOK" ADD CONSTRAINT "SYS_C007675" CHECK ("BOOK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##INSLIB"."BOOK" ADD CONSTRAINT "SYS_C007676" CHECK ("BOOK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table BOOK
-- ----------------------------
ALTER TABLE "C##INSLIB"."BOOK" ADD CONSTRAINT "BOOK_AD_FK" FOREIGN KEY ("ADMIN_ID") REFERENCES "C##INSLIB"."ADMIN" ("ADMIN_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##INSLIB"."BOOK" ADD CONSTRAINT "BOOK_PUB_FK" FOREIGN KEY ("PUBLISHER_NAME") REFERENCES "C##INSLIB"."PUBLISHER" ("PUBLISHER_NAME") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##INSLIB"."BOOK" ADD CONSTRAINT "SYS_C007678" FOREIGN KEY ("AUTHOR_ID") REFERENCES "C##INSLIB"."AUTHOR" ("AUTHOR_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
