/*
 Navicat Premium Data Transfer

 Source Server         : Oracle
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Host           : localhost:1521
 Source Schema         : C##INSLIB

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 22/02/2022 20:39:52
*/


-- ----------------------------
-- Table structure for ISSUE_LIST
-- ----------------------------
DROP TABLE "C##INSLIB"."ISSUE_LIST";
CREATE TABLE "C##INSLIB"."ISSUE_LIST" (
  "ISSUE_ID" NUMBER VISIBLE NOT NULL,
  "MEMBER_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "BOOK_ID" NUMBER(10,0) VISIBLE NOT NULL,
  "ISSUE_DATE" DATE VISIBLE DEFAULT SYSDATE,
  "ADMIN_ID" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ISSUE_LIST
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table ISSUE_LIST
-- ----------------------------
ALTER TABLE "C##INSLIB"."ISSUE_LIST" ADD CONSTRAINT "SYS_C007805" PRIMARY KEY ("ISSUE_ID");

-- ----------------------------
-- Checks structure for table ISSUE_LIST
-- ----------------------------
ALTER TABLE "C##INSLIB"."ISSUE_LIST" ADD CONSTRAINT "SYS_C007802" CHECK ("ISSUE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##INSLIB"."ISSUE_LIST" ADD CONSTRAINT "SYS_C007803" CHECK ("MEMBER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##INSLIB"."ISSUE_LIST" ADD CONSTRAINT "SYS_C007804" CHECK ("BOOK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table ISSUE_LIST
-- ----------------------------
ALTER TABLE "C##INSLIB"."ISSUE_LIST" ADD CONSTRAINT "ISS_AD_FK" FOREIGN KEY ("ADMIN_ID") REFERENCES "C##INSLIB"."ADMIN" ("ADMIN_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##INSLIB"."ISSUE_LIST" ADD CONSTRAINT "ISS_BK_FK" FOREIGN KEY ("BOOK_ID") REFERENCES "C##INSLIB"."BOOK" ("BOOK_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##INSLIB"."ISSUE_LIST" ADD CONSTRAINT "ISS_MEM_FK" FOREIGN KEY ("MEMBER_ID") REFERENCES "C##INSLIB"."MEMBER" ("MEMBER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
