SELECT BOOK.BOOK_ID, BOOK.BOOK_NAME, AUTHOR.AUTHOR_NAME, BOOK.PUBLISHER_NAME, BOOK.STATUS, BOOK.LANGUAGE, BOOK.YEAR,
    BOOK.EDITION, BOOK.NO_OF_PAGES,COVER_IMAGE
    FROM BOOK
    JOIN AUTHOR ON (BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID)
    JOIN BOOKLIST_ACADEMIC ON (BOOK.BOOK_ID = BOOKLIST_ACADEMIC.BOOK_ID)
    WHERE (BOOK.BOOK_NAME LIKE :1)
    OR (BOOK.STATUS LIKE :1)
    OR (AUTHOR.AUTHOR_NAME LIKE :1)
    OR (AUTHOR.AUTHOR_ID LIKE :1)
    OR (BOOK.PUBLISHER_NAME LIKE :1)
    OR (BOOK.LANGUAGE LIKE :1)
    OR (BOOKLIST_ACADEMIC.SUBJECT LIKE :1)
    OR (BOOKLIST_ACADEMIC.DEPARTMENT LIKE :1)
    ORDER BY AUTHOR.AUTHOR_NAME

SELECT NAME, DESIGNATION, DEPT, ID, DATE_OF_BIRTH, ADDRESS, EMAIL, PHONE_NUMBER, BLOOD_GROUP, RESIDENCE
    FROM APPLICANT
    WHERE ID LIKE :1
    ORDER BY NAME

DECLARE
NEW_MEMBER_ID NUMBER(10);
BEGIN
    GENERATE_MEMBER_ID(1,NEW_MEMBER_ID);
    INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, EMAIL, PHONE_NUMBER, BLOOD_GROUP, DATE_OF_BIRTH, ADMIN_ID, PASSWORD,NUM_OF_ISSUE,DEPT)
    VALUES (NEW_MEMBER_ID,:1,:2,:3,:4,:5,:6,:7,:8,:9);
    INSERT INTO MEMBER_STUDENT (STUDENT_ID, RESIDENCE, MEMBER_ID) VALUES (:10,:11,NEW_MEMBER_ID);
END;   

DECLARE
 NEW_BOOK_ID NUMBER(10);
BEGIN
    GENERATE_BOOK_ID(2,NEW_BOOK_ID);
    INSERT INTO BOOK (BOOK_ID, BOOK_NAME, AUTHOR_ID, PUBLISHER_NAME, COVER_IMAGE, STATUS, DATE_OF_ARRIVAL, YEAR,
    EDITION, NO_OF_PAGES, LANGUAGE, ADMIN_ID) VALUES (NEW_BOOK_ID,:1,:2,:3,:4,:5,:6,:7,:8,:9,:10,:11);
    INSERT INTO BOOKLIST_ACADEMIC (BOOK_ID, SUBJECT, DEPARTMENT) VALUES (NEW_BOOK_ID,:12,:13);
END;

DECLARE
DAYS NUMBER(10);
BEGIN
FOR R IN (SELECT ISSUE_LIST.ISSUE_DATE, MEMBER.FINE, MEMBER.MEMBER_ID FROM ISSUE_LIST JOIN MEMBER ON ISSUE_LIST.MEMBER_ID = MEMBER.MEMBER_ID)
    LOOP
        SELECT TRUNC(SYSDATE - R.ISSUE_DATE) INTO DAYS
        FROM DUAL;
        IF(DAYS >14) THEN
            UPDATE MEMBER SET FINE = FINE+ (DAYS - 14) * 5
            WHERE MEMBER_ID = R.MEMBER_ID;
        END IF;
    END LOOP;
END;

SELECT MEMBER_ID, MEMBER_NAME, TYPE, EMAIL, PHONE_NUMBER, BLOOD_GROUP FROM MEMBER ORDER BY BLOOD_GROUP
SELECT B.COVER_IMAGE, B.BOOK_NAME,B.BOOK_ID, A.AUTHOR_NAME, M.MEMBER_NAME,M.MEMBER_ID, RL.REVIEW_TEXT FROM  MEMBER M JOIN REVIEW_LIST RL ON (M.MEMBER_ID = RL.MEMBER_ID) JOIN BOOK B ON (RL.BOOK_ID = B.BOOK_ID) JOIN AUTHOR A ON (B.AUTHOR_ID = A.AUTHOR_ID) WHERE UPPER(B.BOOK_TYPE) LIKE '%ACADEMIC%' ORDER BY B.BOOK_NAME
SELECT IMAGE,TITLE,TO_CHAR(NEWS_DATE, 'DD.MM.YYYY') AS NEWS_DATE,DESCRIPTION FROM NEWS_AND_EVENTS ORDER BY NEWS_DATE DESC

SELECT B.BOOK_NAME, A.AUTHOR_NAME, B.STATUS, B.COVER_IMAGE,B.DATE_OF_ARRIVAL
FROM BOOK B JOIN AUTHOR A ON (A.AUTHOR_ID = B.AUTHOR_ID) WHERE ((SYSDATE-B.DATE_OF_ARRIVAL)/30)<=3 ORDER BY B.DATE_OF_ARRIVAL

SELECT B.BOOK_ID, B.BOOK_NAME, A.AUTHOR_NAME, B.PUBLISHER_NAME, B.STATUS, B.LANGUAGE, B.YEAR, B.EDITION, B.NO_OF_PAGES, B.COVER_IMAGE FROM BOOKLIST_ACADEMIC AC JOIN BOOK B ON (AC.BOOK_ID = B.BOOK_ID) JOIN AUTHOR A ON (A.AUTHOR_ID = B.AUTHOR_ID) WHERE UPPER(AC.DEPARTMENT) LIKE '%${info.child}%' AND UPPER(AC.SUBJECT) LIKE '%${info.grandchild}%' ORDER BY A.AUTHOR_NAME

SELECT B.BOOK_ID, B.BOOK_NAME, A.AUTHOR_NAME, B.PUBLISHER_NAME, B.STATUS, B.BOOK_TYPE,B.DATE_OF_ARRIVAL, B.LANGUAGE, B.YEAR, B.EDITION, B.COVER_IMAGE
FROM BOOK B JOIN AUTHOR A ON (A.AUTHOR_ID = B.AUTHOR_ID) WHERE ((SYSDATE-B.DATE_OF_ARRIVAL)/30)<=3 ORDER BY B.DATE_OF_ARRIVAL                            

SELECT F.BOOK_ID,B.BOOK_NAME,A.AUTHOR_NAME FROM FAV_LIST F JOIN BOOK B ON(F.BOOK_ID = B.BOOK_ID) 
JOIN AUTHOR A ON(B.AUTHOR_ID=A.AUTHOR_ID) WHERE F.MEMBER_ID = :1 ORDER BY A.AUTHOR_NAME


                         
