--total 3 triggers and 6 PROCEDURE/functions  2 sequences 5 complex queries

--trigger to delete all instances of a book when it is deleted from main book table
CREATE OR REPLACE TRIGGER DELETE_BOOK
BEFORE DELETE
ON BOOK
FOR EACH ROW
DECLARE
    V_BOOK_ID NUMBER(10);
    V_MEMBER_ID NUMBER(10,0);
BEGIN
    V_BOOK_ID := :OLD.BOOK_ID;
    BEGIN
       DELETE FROM FAV_LIST
       WHERE FAV_LIST.BOOK_ID = V_BOOK_ID;

       DELETE FROM BOOKLIST_ACADEMIC
       WHERE BOOKLIST_ACADEMIC.BOOK_ID = V_BOOK_ID;

       DELETE FROM BOOKLIST_OTHERS
       WHERE BOOKLIST_OTHERS.BOOK_ID = V_BOOK_ID;

       DELETE FROM REVIEW_LIST
       WHERE REVIEW_LIST.BOOK_ID = V_BOOK_ID;
       --DBMS_OUTPUT.PUT_LINE('DELETED');
    END;

    FOR R IN (SELECT * FROM ISSUE_LIST WHERE ISSUE_LIST.BOOK_ID = V_BOOK_ID)
    LOOP
        V_MEMBER_ID := R.MEMBER_ID;
        UPDATE MEMBER SET MEMBER.NUM_OF_ISSUE = (MEMBER.NUM_OF_ISSUE - 1)
        WHERE MEMBER_ID = V_MEMBER_ID;
    END LOOP;
    BEGIN
        DELETE FROM ISSUE_LIST
        WHERE ISSUE_LIST.BOOK_ID = V_BOOK_ID;

    END;
END;
/

--trigger to update book status and number_of_issue of member when an issue record is inserted
CREATE OR REPLACE TRIGGER ISSUE_BOOK
BEFORE INSERT
ON ISSUE_LIST
FOR EACH ROW
DECLARE
    V_BOOK_ID NUMBER(10);
    V_MEMBER_ID NUMBER(10,0);
BEGIN
    V_BOOK_ID := :NEW.BOOK_ID;
    V_MEMBER_ID := :NEW.MEMBER_ID;
    UPDATE MEMBER SET MEMBER.NUM_OF_ISSUE = (MEMBER.NUM_OF_ISSUE + 1)
    WHERE MEMBER_ID = V_MEMBER_ID;

    UPDATE BOOK SET BOOK.STATUS = 'NOT AVAILABLE'
    WHERE BOOK.BOOK_ID = V_BOOK_ID;
   -- DBMS_OUTPUT.PUT_LINE('INSERTED');
END;
/

--trigger to update book status and number_of_issue of member when an issue record is deleted
CREATE OR REPLACE TRIGGER DELETE_ISSUE
BEFORE DELETE
ON ISSUE_LIST
FOR EACH ROW
DECLARE
    V_BOOK_ID NUMBER(10);
    V_MEMBER_ID NUMBER(10,0);
BEGIN
    V_BOOK_ID := :OLD.BOOK_ID;
    V_MEMBER_ID := :OLD.MEMBER_ID;

    UPDATE BOOK SET BOOK.STATUS = 'AVAILABLE'
    WHERE BOOK_ID = V_BOOK_ID;

    UPDATE MEMBER SET MEMBER.NUM_OF_ISSUE = (MEMBER.NUM_OF_ISSUE - 1)
    WHERE MEMBER_ID = V_MEMBER_ID;

END;
/

-- function to generate book and memeber id automatically according to subcategory i.e. started by 1/2/3
CREATE OR REPLACE FUNCTION ID_GENERATOR(N IN NUMBER,ID IN NUMBER)
RETURN NUMBER IS
 I NUMBER(10) := N;
 APPEND NUMBER := ID;
 ANSWER NUMBER;
BEGIN
  WHILE I > 0
  LOOP
    I := I/10;
    APPEND := APPEND * 10;
  END LOOP;
  ANSWER := APPEND + N;
  RETURN ANSWER;
END;
/

CREATE SEQUENCE BOOK__ID__SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE MEMBER__ID__SEQ INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE PROCEDURE GENERATE_BOOK_ID(PRE_ID IN NUMBER,REQ_ID OUT NUMBER) IS
BEGIN
   REQ_ID := ID_GENERATOR( BOOK__ID__SEQ.nextval, PRE_ID);
END;
/

CREATE OR REPLACE PROCEDURE GENERATE_MEMBER_ID(PRE_ID IN NUMBER,REQ_ID OUT NUMBER) IS
BEGIN
   REQ_ID := ID_GENERATOR( MEMBER__ID__SEQ.nextval, PRE_ID);
END;
/

